name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Dotnet Toolchain
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - run: dotnet build src/AspnetPerf.MinimalApi/AspnetPerf.MinimalApi.csproj

  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: ./src/AspnetPerf.MinimalApi/
          load: true
          tags: aspnet-perf:latest
